//! FFI Bridge — the only crate Dart talks to.
//!
//! This crate exposes a minimal, stable public API to Flutter via
//! `flutter_rust_bridge`. **No torrent logic lives here.** All
//! implementation is delegated to `torrent_core`.
//!
//! ## Codegen
//!
//! The `frb_generated` module is auto-generated by running:
//! ```powershell
//! .\scripts\generate_bridge.ps1
//! ```
//! Do **not** edit `frb_generated.rs` manually.
//!
//! ## Crate output
//!
//! The compiled library is named `libtor_stream.so` (Android) or
//! `tor_stream.dll` / `libtor_stream.dylib` (desktop) — matching the
//! Flutter package name.

// ── Auto-generated bridge code (created by flutter_rust_bridge_codegen) ──────
mod frb_generated;

// ── Public API surface ────────────────────────────────────────────────────────
pub mod api;
pub mod types;
